### ISSUE TITLE
[minor] 404 on these three resources

### ISSUE THREAD

**Issue by sajacy** [newamericafoundation/drones.newamerica.org#51]
the three JS scripts referenced on the lines starting at:
https://github.com/newamericafoundation/drones/blob/master/index.html#L339

no longer exist on the site and cause a 404 / script error in the Dev Tools console.

I like a clean console. :)

**Comment by kakaes** [comment]
Thanks for noticing Jeff! Georgia maybe we can ask Ross what the story is?

**Comment by georgiamoon** [comment]
I'll check it out while I'm doing some dataviz work today.

**Comment by georgiamoon** [comment]
Oh -- I think it's just an https issue. i'll fix.

On Tue, Feb 16, 2016 at 10:10 AM, Georgia Bullen <
georgia@opentechinstitute.org> wrote:

> I'll check it out while I'm doing some dataviz work today.
> On Feb 16, 2016 7:10 AM, "kakaes" <notifications@github.com> wrote:
>
>> Thanks for noticing Jeff! Georgia maybe we can ask Ross what the story is?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/newamericafoundation/drones/issues/51#issuecomment-184659033>
>> .
>>
>


-- 
Georgia Bullen
Open Technology Institute <http://newamerica.org/oti/> @ New America
<http://newamerica.org>
740 15th Street NW, Suite 900, Washington DC, 20005
@georgiamoon <http://twitter.com/georgiamoon>
